version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_shortener
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  url-shortener-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lowes/url-shortener
    restart: on-failure
    depends_on:
      - mysql-local
    ports:
      - 8080:8080
      
  url-shortener-frontend:
    image: lowes/frontend
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_HOST: http://localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - url-shortener-backend
